# Generated by Django 2.0.6 on 2018-06-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsubmission',
            name='submission_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
