# Generated by Django 2.0.6 on 2018-06-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelresponse',
            name='model_submission',
        ),
    ]
