# Generated by Django 2.0.7 on 2018-09-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='is_baseline',
            field=models.BooleanField(default=False),
        ),
    ]
