# Generated by Django 2.0.6 on 2018-07-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_metric_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='info',
        ),
        migrations.AddField(
            model_name='modelsubmission',
            name='evaluationdatasets',
            field=models.ManyToManyField(to='orm.EvaluationDataset'),
        ),
    ]
