# Generated by Django 2.0.7 on 2018-09-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_model_is_baseline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationdataset',
            name='baselines',
            field=models.ManyToManyField(null=True, to='orm.Model'),
        ),
    ]
