# Generated by Django 2.0.7 on 2018-09-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0004_auto_20180903_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
