# Generated by Django 2.0.6 on 2018-07-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0004_automaticevaluation_model_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
