# Generated by Django 2.0.6 on 2018-07-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0005_model_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='info',
            field=models.CharField(default='https://github.com/chateval/application/tree/master/eval', max_length=200),
            preserve_default=False,
        ),
    ]
