# Generated by Django 2.0.7 on 2018-11-08 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0007_patch_admin'),
    ]

    operations = [
        migrations.RunSQL(
            sql=['ALTER TABLE EvaluationDatasetText MODIFY prompt_text LONGTEXT CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci'],
            reverse_sql=['ALTER TABLE EvaluationDatasetText MODIFY prompt_text LONGTEXT']  
        )
    ]
