# Generated by Django 2.0.6 on 2018-07-11 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0007_auto_20180711_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='humanevaluationsabcomparison',
            old_name='prompt_id',
            new_name='prompt',
        ),
    ]
