# Generated by Django 2.0.7 on 2018-11-08 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0008_switch_to_utf8mb4_columns2'),
    ]

    operations = [
        migrations.RunSQL(
            sql=['ALTER TABLE django_admin_log MODIFY object_repr VARCHAR(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL'],
            reverse_sql=['ALTER TABLE django_admin_log MODIFY object_repr VARCHAR(200) NOT NULL']
        )
    ]