# Generated by Django 2.0.6 on 2018-06-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SplashBaseline',
            new_name='Baseline',
        ),
        migrations.RenameModel(
            old_name='SplashDataset',
            new_name='Dataset',
        ),
        migrations.AlterModelTable(
            name='baseline',
            table='Baseline',
        ),
        migrations.AlterModelTable(
            name='dataset',
            table='Dataset',
        ),
    ]
