# Generated by Django 2.0.6 on 2018-06-20 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180619_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='repo_info',
            new_name='repo_location',
        ),
    ]
