# Generated by Django 2.0.6 on 2018-06-18 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180614_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationdatasettext',
            name='evaluationdataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.EvaluationDataset'),
        ),
        migrations.AlterField(
            model_name='evaluationdatasettext',
            name='prompt_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
